odoo:
  image: dstadel/odoo10.0
  ports:
    - ${client_port}:8069
  links:
    - db
  volumes:
    - ${client_path}odoo_webdata:/var/lib/odoo
    - ${client_path}odoo_config:/etc/odoo
    - ${client_path}odoo_addons:/mnt/extra-addons
  environment:
    - LOCAL_USER_ID="id -u $USER"
    
db:
  image: postgres
  environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=${db_password}
    - PGDATA=/var/lib/postgresql/data/pgdata
    - LOCAL_USER_ID="id -u $USER"
  volumes:
    - ${client_path}odoo_db_data:/var/lib/postgresql/data/pgdata
