odoo:
  image: dstadel/odoo10.0:v0.1
  ports:
    - ${client_port}:8069
  links:
    - db
  volumes:
    - odoo_webdata:/var/lib/odoo
    - odoo_config:/etc/odoo
    - /home/dstadel/che_data/instance/data/workspaces/python27/extra-addons:/mnt/extra-addons
    
db:
  image: postgres
  environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=${db_password}
    - PGDATA=/var/lib/postgresql/data/pgdata
  volumes:
    - odoo_db_data:/var/lib/postgresql/data/pgdata
