odoo:
  image: dstadel/odoo10.0
  #image: odoo
  ports:
    - ${client_port}:8069
  links:
    - db
  volumes:
    - ${client_path}odoo_webdata:/var/lib/odoo
    - ${client_path}odoo_config:/etc/odoo
    - ${client_path}odoo_addons:/mnt/extra-addons
    #labels:
    # Make db only run on hosts that do not have a availability=temporal label
    #io.rancher.scheduler.affinity:host_label: availability=permanent

db:
  image: postgres
  environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=${db_password}
    - PGDATA=/var/lib/postgresql/data/pgdata
  volumes:
    - ${client_path}odoo_db_data:/var/lib/postgresql/data/pgdata
  #labels:
    # Make db only run on hosts that do not have a availability=temporal label
    #io.rancher.scheduler.affinity:host_label: availability=permanent
