.catalog:
  name: "Odoo"
  version: v0.1-dstadel
  description: "Sistema de gestión integral de los recursos de una empresa, como Microsoft SAP."
  uuid: odoo-0
  questions:
    - variable: client_port
      description: "Port to access Odoo"
      label: "Client Port"
      required: true
      default: "8020"
      type: "int"
    - variable: client_path
      description: "Root path of odoo files"
      label: "Client Path"
      required: true
      default: "/home/dstadel/odoo10-dev0x/"
      type: "string"
    - variable: db_password
      description: "Password for database"
      label: "Password (default: odoo)"
      required: true
      default: "odoo"
      type: "password"
